version: '3'

tasks:
  default:
    silent: true
    desc: "Show list of all available Taskfile commands"
    cmds:
      - task --list --color

  build:
    desc: "Build Docker image"
    cmds:
      - docker build --no-cache -t fauxy .

  down:
    desc: "Stop and remove playground container"
    cmds:
      - docker stop fauxy-app
      - docker rm fauxy-app

  up:
    desc: "Start playground container"
    cmds:
      - docker start fauxy-app || docker run -d --name fauxy-app -p 5173:5173 -v ${PWD}:/app fauxy

  logs:
    desc: "Follow logs from the playground container with tail output"
    cmds:
      - docker logs -f --tail 100 fauxy-app

  bash:
    desc: "Open interactive shell session inside the running playground container"
    cmds:
      - docker exec -it fauxy-app sh
